export const USER_REQUEST = "USER_REQUEST";
export const USER_OBSERVATIONS = "USER_OBSERVATIONS";
export const USER_SUCCESS = "USER_SUCCESS";
export const USER_OBS_SUCCESS = "USER_OBS_SUCCESS";
export const USER_ERROR = "USER_ERROR";
